# for creating these resources it requires the user to be logged in as system admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: javascript-example-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: javascript-example-operator-edit-resources
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: javascript-example-operator
    namespace: myproject
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: javascript-example-operator
  labels: &default-labels
    app.kubernetes.io/name: javascript-example-operator
    app.kubernetes.io/version: v0.1.5-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels: *default-labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *default-labels
    spec:
      serviceAccountName: javascript-example-operator
      containers:
      - name: javascript-example-operator
        image: radanalyticsio/javascript-example-operator:latest
        env:
        - name: CRD
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        imagePullPolicy: IfNotPresent

