apiVersion: v1
kind: ServiceAccount
metadata:
  name: javascript-example-operator
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: edit-resources
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "services", "configmaps"]
  verbs: ["create", "delete", "deletecollection", "get", "list", "update", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: javascript-example-operator-edit-resources
roleRef:
  kind: Role
  name: edit-resources
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: javascript-example-operator
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: javascript-example-operator
  labels: &default-labels
    app.kubernetes.io/name: javascript-example-operator
    app.kubernetes.io/version: v0.1.5-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels: *default-labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *default-labels
    spec:
      serviceAccountName: javascript-example-operator
      containers:
      - name: javascript-example-operator
        image: radanalyticsio/javascript-example-operator:latest
        #env:
        #- name: WATCHED_NAMESPACE
        #  value: myproject
        #- name: CRD
        #  value: "true"
        #- name: COLORS
        #  value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        imagePullPolicy: IfNotPresent

